# Generated by Django 4.2.17 on 2025-01-03 15:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chaiVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='chais/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('BL', 'Black Tea'), ('GR', 'Green Tea'), ('HR', 'Herbal Tea'), ('MS', 'Masala Tea')], max_length=2)),
            ],
        ),
    ]
