# Generated by Django 4.2.17 on 2025-01-04 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erisapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivariety',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
