# Generated by Django 4.2.17 on 2025-01-04 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erisapp', '0002_chaivariety_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chaivariety',
            name='image',
        ),
    ]
