# Generated by Django 4.2.17 on 2025-01-04 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erisapp', '0003_remove_chaivariety_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivariety',
            name='image',
            field=models.ImageField(default='', upload_to='chais/'),
        ),
    ]
